name: presence
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  cloud_firestore: 4.5.0
  convex_bottom_bar: 3.2.0
  cupertino_icons: ^1.0.2
  firebase_auth: 4.4.0
  firebase_core: ^2.9.0
  firebase_storage: 11.1.0
  flutter:
    sdk: flutter
  geocoding: 2.0.4
  geolocator: 8.2.0
  get: 4.6.5
  image_picker: 0.8.7+2
  intl: 0.17.0
  syncfusion_flutter_datepicker: ^21.2.3

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
